[package]
name = "tsid-rust"
version = "0.1.0"
edition = "2021"
rust-version = "1.85.0"
description = "A Rust library for generating TSID (Time-Sorted ID) - a timestamp-based distributed unique identifier"
license = "MIT"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
opt-level = 0
debug = true

[dependencies]
